kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels: 
# set your lab user name
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
# set your lab user name
        app: {{ .Release.Name }}
    spec:
      containers:
        - resources: {}
          name: {{ .Release.Name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          terminationMessagePath: /dev/termination-log
          name: {{ .Release.Name }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10